### ISSUE TITLE
Build the meta repository

### ISSUE THREAD

**Issue by jasinai** [Qabel/qabel-drop#18]
If we change the drop server, qabel-core could be broken.
I think, we should also test all the other repositories. What do you think?

**Comment by thechauffeur** [comment]
I totally agree with that -- we should use the meta repository for Travis just like we do with the others.

**Comment by NanNor** [comment]
Should I replace or edit the .travis.yml in qabel-drop?

**Comment by thechauffeur** [comment]
@NanNor Speaking in git language it doesn't matter as long as the file name does will still be the same.
