### ISSUE TITLE
add postgresql to documentation

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-drop#27]
The readme should contain some information about the postgresql-setup or at least that it's required. Additionally some information if and how qabel-drop can be configured to use redis would be useful (example config file).

(introduced in https://github.com/Qabel/qabel-drop/commit/4611e3f3aa5c8b2235c7d763eb92cd9b67a59be8 )

**Comment by jasinai** [comment]
Oh, I forgot to update it. Thanks for reminding me. :)

**Comment by julianseeger** [comment]
When addressing this, please check https://github.com/Qabel/qabel-desktop#server-test-instances for missing / superfluous things. Maybe it can get optimized.

**Comment by jasinai** [comment]
The "Qabel Accounting Server" link points to the qabel-drop readme.
I think, it would be better to remove the set up from qabel-desktop and only have the information in the other repositories, as soon as they are up-to-date. So we don't have to update the desktop repository, if some things change in the servers.
