### ISSUE TITLE
sudo needed for pip...

### ISSUE THREAD

**Issue by roeslpa** [Qabel/qabel-drop#31]
When executing `pip install -r requirements.txt` following error occurred:
`error: could not create '/usr/local/lib/python2.7/dist-packages/flask': Permission denied`
By giving it root permissions it worked properly.

**Comment by audax** [comment]
You should install it in a virtualenv (which is not mentioned in the readme.)

    virtualenv --python=python3.4 ../venv
    source ../venv/bin/activate
    pip install -r requirements.txt

**Comment by roeslpa** [comment]
Yes I did this. Should someone add it to the readme or is it obvious?

**Comment by thechauffeur** [comment]
You can add this to the readme.
