### ISSUE TITLE
Etags instead of modified time

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-drop#45]
Modified dates are weird and Etags are nice. We just need a way to query drop messages with etags instead of timestamps.

**Comment by enkore** [comment]
Guess we could just build a hash from the drops' contents and use that as an ETag? Besides that I don't have many ideas that would fit this.

**Comment by enkore** [comment]
If the clients handle the Last-Modified date like an ETag (i.e. only *store*, never *manipulate* or *generate* it), then there is no problem with time zones, clock skew, ... . This has the advantage over ETags that we can still just send new drop messages, and don't need to resend all drop messages for every request.

**Comment by audax** [comment]
Last-Modified has only seconds, not milliseconds.

Each drop message should have an Etag which only has to be unique for the drop id. The ETag in the response of a GET request is the Etag of the newest drop message. A POST request has no Etag. The Etag in the request of a GET request is the Etag of the last known drop message.

The Etag can be a random string, the last-modified time or whatever. It just has to be unique together with the drop id.

**Comment by enkore** [comment]
> Each drop message should have an Etag which only has to be unique for the drop id. The ETag in the response of a GET request is the Etag of the newest drop message.

Aha, now that makes a lot more sense. Ok.
